<?php $this->layout('layout::default', ['title' => 'Edit Blog']) ?>

<h1>Edit Post</h1>

<?php foreach ($errors as $key => $value) :?>
    <strong><?= ucwords($key) ?></strong>: <?=current($value)?><br>
<?php endforeach;?>
<form method="POST" action="">
    <input type="hidden" id="id" name="id" value="<?= $post->getId() ?>" >
    <div class="form-group">
        <label class="control-label" for="title">Post Title</label>
        <input type="text" class="form-control" id="title" name="title" value="<?= $post->getTitle() ?>" >
    </div>
    <div class="form-group">
        <label class="control-label" for="text">Post Text</label>
        <textarea class="form-control" id="text" name="text" rows="7"><?= $post->getText() ?></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>